Implement datetime and Junit tests
shashd/voc_mp_group3 pull request #4
Opened 2021-09-21 15:03 UTC by shashd

2021-09-22 15:58 UTC, avinkadir requested changes
Great job! The code looks great overall but we just have a few suggestions to further improve it. First, we saw that code coverage is a bit low but we understand that it would be difficult to get a high coverage. Perhaps you could write a few tests for today() and __str__ to improve it?

2021-09-22 16:11 UTC, yuch3628 requested changes

2021-09-22 16:11 UTC, yuch3628 commented on junit_tests/DateTimeTest.java
> +        // use empty args and kwargs to create instance
Great comments ! We think they make it easier to understand what you are testing.

2021-09-22 16:11 UTC, yuch3628 commented on python/common/org/python/stdlib/datetime/DateTime.java
> +                return org.python.types.Bool.getBool(true);
This code block is not necessary, the method works without it. We think removing it improves the readability of the code.

2021-09-22 16:11 UTC, yuch3628 commented on python/common/org/python/stdlib/datetime/DateTime.java
> +    public org.python.Object __gt__(org.python.Object other){
Good job on this code!

2021-09-22 17:09 UTC, gustavborestam commented
We've added more tests to improve coverage and also simplified Le and Ge functions to make them more readable.

Coverage from 67% -> 89%

2021-09-23 11:39 UTC, yuch3628 approved these changes

2021-09-24 07:03 UTC, avinkadir approved these changes

2021-09-24 07:31 UTC, merged